site_name: AWS DVA-C02 Study Notes
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.suggest
    - toc.integrate
    - content.code.copy
    - content.tooltips
  palette:
    - scheme: default
      primary: blue grey
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 3

nav:
  - Home: index.md
  - Compute:
      - EC2: compute/ec2.md
      - EBS: compute/ebs.md
      - Lambda: compute/lambda.md
      - Elastic Beanstalk: compute/elastic-beanstalk.md
  - Storage:
      - S3: storage/s3.md
  - Security:
      - IAM: security/iam.md
      - Cognito: security/cognito.md
      - KMS: security/kms.md
      - Security Manager: security/security-manager.md
  - Networking:
      - API Gateway: networking/api-gateway.md
      - CloudFront: networking/cloudfront.md
      - Route 53: networking/route53.md
  - Security & Networking:
      - Security Groups & NACLs: security-networking/security-groups-nacls.md
      - HTTPS: security-networking/https.md
  - Database:
      - DynamoDB: database/dynamodb.md
      - RDS: database/rds.md
  - Messaging:
      - SQS: messaging/sqs.md
      - Kinesis: messaging/kinesis.md
  - Integration:
      - Step Functions: integration/step-functions.md
  - Scaling:
      - Auto Scaling Groups: scaling/auto-scaling-groups.md
  - Load Balancing:
      - Load Balancers: load-balancing/load-balancers.md
  - Debug:
      - X-Ray: debug/xray.md
  - Deployment:
      - SAM (Serverless Application Model): deployment/sam.md
  - General:
      - General Notes: general/general.md
      - Must Review: general/must-review.md
